parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  prettier/prettier: "error"
  @typescript-eslint/no-unused-vars: "warn"
  @typescript-eslint/explicit-function-return-type: "off"

